# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  spa-lit:
    taskfile: Taskfile.SpaLit.yml
  node-stup:
    taskfile: Taskfile.Node.yml
  pw:
    taskfile: Taskfile.Playwright.yml

tasks:
  default:
    cmds:
      - task --list
    silent: true
