FROM miracle-docker-intern.jfrog.io/docker-intern/devcontainer.debian.iknowagentic:0.0.1

USER root

RUN apt-get update && \
    apt-get install -y iproute2

RUN curl -sL https://taskfile.dev/install.sh | sh -s -- -d -b /usr/local/bin

RUN dotnet tool install --tool-path /usr/local/bin Microsoft.Playwright.CLI

USER container-user

RUN npm install -g @anthropic-ai/claude-code && \
    npm install -g @playwright/mcp@latest

USER container-user
