name: playwright-playground-debian
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.debian
    volumes:
      - ../..:/xyz:cached
    # Vigtigt for Playwright i containere:
    cap_add:
      - SYS_ADMIN
    ports:
      - "6081:6080"
    command: sleep infinity
    networks:
      - internal

networks:
  internal:
    driver: bridge
