services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.devmachine
    volumes:
      - ../..:/xyz:cached
    command: sleep infinity
    networks:
      - internal

networks:
  internal:
    driver: bridge
